name: first_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/pic-1.jpg
    - assets/pic-2.jpg
    - assets/welcome.jpg

  fonts:
    family: IndieFlower
    fonts:
     asset: fonts/IndieDlower-Regular.ttf
