name: first_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  # camera: ^0.11.0+2
  # gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/pic-1.jpg
    - assets/pic-2.jpg
    - assets/welcome.jpg
    - assets/avatar.jpg

  # fonts:
  #   family: IndieFlower
  #   fonts:
  #    asset: fonts/IndieDlower-Regular.ttf
